### ISSUE TITLE
UnDocumented dependency 

### ISSUE THREAD

**Issue by wgaylord** [dividuum/fastmc#4]
The dependancy on gevent is undocumented. It would be helpful if it was.

**Comment by wgaylord** [comment]
Nvm. That's just  used the example. Sorry. Should have looked better before opening this.

**Comment by dividuum** [comment]
No problem. Enjoy hacking minecraft :-)

**Comment by wgaylord** [comment]
Yeah. I just change it from using gevent to just normal socket.

And I going to try and use this for logging into a forge server. (Going to make it think I have all the mods and other stuff. (As the ping sends back what mods the server has.))
